// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54LRAbfMYu3fpDcwOX1_nFynDqZB_f4M',
    appId: '1:586650216184:web:43348bbb20a70608887d0d',
    messagingSenderId: '586650216184',
    projectId: 'gymrat-8ec74',
    authDomain: 'gymrat-8ec74.firebaseapp.com',
    storageBucket: 'gymrat-8ec74.firebasestorage.app',
    measurementId: 'G-E42M1FXFG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSKGrH09FdbT0Qmx78OIU0Xw1_JN-tusk',
    appId: '1:586650216184:android:4c4873b850eed039887d0d',
    messagingSenderId: '586650216184',
    projectId: 'gymrat-8ec74',
    storageBucket: 'gymrat-8ec74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjeTTEgUNo7JjgSKLh0P7NUuIIcrnLJmE',
    appId: '1:586650216184:ios:87930adb03f6fc5a887d0d',
    messagingSenderId: '586650216184',
    projectId: 'gymrat-8ec74',
    storageBucket: 'gymrat-8ec74.firebasestorage.app',
    androidClientId: '586650216184-mo6ojeb9rj8kjmtrt1gj01q49hco28ph.apps.googleusercontent.com',
    iosClientId: '586650216184-kqb34biqt00r1iflqdg1b59iagqvk1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjeTTEgUNo7JjgSKLh0P7NUuIIcrnLJmE',
    appId: '1:586650216184:ios:87930adb03f6fc5a887d0d',
    messagingSenderId: '586650216184',
    projectId: 'gymrat-8ec74',
    storageBucket: 'gymrat-8ec74.firebasestorage.app',
    androidClientId: '586650216184-mo6ojeb9rj8kjmtrt1gj01q49hco28ph.apps.googleusercontent.com',
    iosClientId: '586650216184-kqb34biqt00r1iflqdg1b59iagqvk1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
